# PyTorch Tutorial for Deep Learning

because personally, don't like tensorflow, also it works well with CUDA, but I use a macbook, unfortunately.

In [1]:
# basic imports
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# read data from the folder called "digit-recognizer"

train = pd.read_csv("digit-recognizer/train.csv")
test = pd.read_csv("digit-recognizer/test.csv")

# check the data
print(train.head())
print(test.head())

   label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         

### Basis of PyTorch

Let's first see and learn some basics of PyTorch, matrixes are basis for everything, and in pytorch they are called tensors. Let's see them in action

In [3]:
array = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
array = np.array(array)

print("Array Type: {}".format(type(array)))
print("Array Shape: {}".format(array.shape))

print("Array:\n{}".format(array))

Array Type: <class 'numpy.ndarray'>
Array Shape: (3, 3)
Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


This is the numpy array, now let's take a look at the pytorch tensor

In [4]:
import torch 

tensor = torch.Tensor(array)

print("Tensor Type: {}".format(tensor.type()))
print("Tensor Shape: {}".format(tensor.shape))

print("Tensor:\n{}".format(tensor))

Tensor Type: torch.FloatTensor
Tensor Shape: torch.Size([3, 3])
Tensor:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Let's compare numpy and tensor

In [5]:

# numpy ones
print("Numpy {}\n".format(np.ones((2,3))))

# pytorch ones
print(torch.ones((2,3)))

Numpy [[1. 1. 1.]
 [1. 1. 1.]]

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# numpy random
print("Numpy {}\n".format(np.random.rand(2,3)))

# pytorch random
print(torch.rand(2,3))

Numpy [[0.2949288  0.89223082 0.22924258]
 [0.6001842  0.32279372 0.45021756]]

tensor([[0.2685, 0.3230, 0.7728],
        [0.8551, 0.3826, 0.0108]])


We can also convert one to another

1. torch.from_numpy() : From numpy to tensor
2. numpy()            : From tensor to numpy

In [7]:
# random numpy array
array = np.random.rand(2,2)
print("{} {}\n".format(type(array),array))

# from numpy to tensor
from_numpy_to_tensor = torch.from_numpy(array)
print("{}\n".format(from_numpy_to_tensor))

# from tensor to numpy
tensor = from_numpy_to_tensor
from_tensor_to_numpy = tensor.numpy()
print("{} {}\n".format(type(from_tensor_to_numpy),from_tensor_to_numpy))

<class 'numpy.ndarray'> [[0.82708792 0.1120577 ]
 [0.650974   0.61457472]]

tensor([[0.8271, 0.1121],
        [0.6510, 0.6146]], dtype=torch.float64)

<class 'numpy.ndarray'> [[0.82708792 0.1120577 ]
 [0.650974   0.61457472]]



### Basic Maths with PyTorch

In [8]:
# create tensor 
tensor = torch.ones(3,3)
print("\n",tensor)

# Resize
print("{}{}\n".format(tensor.view(9).shape,tensor.view(9)))

# Addition
print("Addition: {}\n".format(torch.add(tensor,tensor)))

# Subtraction
print("Subtraction: {}\n".format(tensor.sub(tensor)))

# Element wise multiplication
print("Element wise multiplication: {}\n".format(torch.mul(tensor,tensor)))

# Element wise division
print("Element wise division: {}\n".format(torch.div(tensor,tensor)))

# Mean
tensor = torch.Tensor([1,2,3,4,5])
print("Mean: {}".format(tensor.mean()))

# Standart deviation (std)
print("std: {}".format(tensor.std()))


 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([9])tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])

Addition: tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

Subtraction: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

Element wise multiplication: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Element wise division: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

Mean: 3.0
std: 1.5811388492584229


### Variables

It accumulates gradient, and since we are using it in Neural Network, that actually use gradients while backpropagating, so we need to handle the gradients

In [9]:
from torch.autograd import Variable
var = Variable(torch.ones(3), requires_grad = True)
print(var)

tensor([1., 1., 1.], requires_grad=True)


Assume we have equation $y = x^2$, define $x = [2,4]$ variable.

After calculation we find that $y = [4,16]$ $(y = x^2)$

Recap $o$ equation is that $o = (1/2)\sum(y) = (1/2)\sum(x^2)$, deriavative of $o = x$

Result is equal to x so gradients are [2,4]

Lets implement

In [10]:
# lets make basic backward propagation
# we have an equation that is y = x^2
array = [2,4]
tensor = torch.Tensor(array)
x = Variable(tensor, requires_grad = True)
y = x**2
print(" y = ",y)



 y =   tensor([ 4., 16.], grad_fn=<PowBackward0>)


In [11]:
# recap o equation o = 1/2*sum(y)
o = (1/2)*sum(y)
print(" o = ",o)



 o =   tensor(10., grad_fn=<MulBackward0>)


In [12]:
# backward
o.backward() # calculates gradients

# As I defined, variables accumulates gradients. In this part there is only one variable x.
# Therefore variable x should be have gradients
# Lets look at gradients with x.grad
print("gradients = ",x.grad)

gradients:  tensor([2., 4.])
